export default data =[
  {
    id:1,
    title:"moins de 8%",
    image:require("../assets/Bodies/under8.png"),
    sexe:"M"
  },
  {
    id:2,
    title:"10-14%",
    image:require("../assets/Bodies/10-14.png"),
    sexe:"M"
  },
  {
    id:3,
    title:"15-18%",
    image:require("../assets/Bodies/15-18.png"),
    sexe:"M"
  },
  {
    id:4,
    title:"22-25%",
    image:require("../assets/Bodies/22-25.png"),
    sexe:"M"
  },
  {
    id:5,
    title:"au-dessus de 30%",
    image:require("../assets/Bodies/over30.png"),
    sexe:"M"
  },
  {
    id:6,
    title:"moins de 15%",
    image:require("../assets/Bodies/under15.png"),
    sexe:"F"
  },
  {
    id:7,
    title:"15-18%",
    image:require("../assets/Bodies/15-18F.png"),
    sexe:"F"
  },
  {
    id:8,
    title:"19-22%",
    image:require("../assets/Bodies/19-22.png"),
    sexe:"F"
  },
  {
    id:9,
    title:"24-30%",
    image:require("../assets/Bodies/24-30.png"),
    sexe:"F"
  },
  {
    id:10,
    title:"au-dessus de 30%",
    image:require("../assets/Bodies/over30F.png"),
    sexe:"F"
  }
]
